# Generated by Django 4.2.9 on 2024-02-09 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_lituser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lituser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
